<a href="https://colab.research.google.com/github/lientzubob/python_basic/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [15]:
import numpy as np
a = np.arange(1000000)
a

array([     0,      1,      2, ..., 999997, 999998, 999999])

In [16]:
list1 = list(np.arange(1000000))

In [17]:
%time for _ in range(10): arr = a * 2

CPU times: user 12.6 ms, sys: 4.94 ms, total: 17.5 ms
Wall time: 24 ms


In [18]:
%time for _ in range(10): list2 = [x * 2 for x in list1]

CPU times: user 2.17 s, sys: 155 ms, total: 2.33 s
Wall time: 2.34 s


In [19]:
data = np.random.randn(2, 3)
data

array([[-0.75309852,  0.48287039, -0.57136123],
       [ 1.46996552, -0.46668719,  0.38503874]])

In [20]:
data * 10

array([[-7.53098517,  4.82870388, -5.7136123 ],
       [14.69965524, -4.66687187,  3.85038743]])

In [21]:
data + data

array([[-1.50619703,  0.96574078, -1.14272246],
       [ 2.93993105, -0.93337437,  0.77007749]])

In [22]:
data.shape

(2, 3)

In [23]:
data.dtype

dtype('float64')

In [24]:
data = [1,2,3,4,5]
arr = np.array(data)
arr

array([1, 2, 3, 4, 5])

In [25]:
data = [[1,2,3,4,5], [6,7,8,9,10]]
arr = np.array(data)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [26]:
arr.ndim

2

In [27]:
arr.shape

(2, 5)

In [28]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [29]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [30]:
np.empty((2,3,2))

array([[[5.03681013e-310, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000]],

       [[0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000]]])

In [31]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [32]:
arr = np.array([1,2,3,4,5])
arr.dtype

dtype('int64')

In [33]:
arr.astype(np.float64).dtype

dtype('float64')

In [34]:
arr = np.array([1.1, 2.2, 3.3, 4.4])
arr.dtype

dtype('float64')

In [35]:
arr.astype(np.int32)

array([1, 2, 3, 4], dtype=int32)

In [36]:
arr = np.array(["1.1", "2.2", "3.3", "4.4"], dtype=np.string_)
arr.astype(float)

array([1.1, 2.2, 3.3, 4.4])

In [38]:
arr = np.array([[
    [1,2,3],
    [4,5,6]
]])
arr

array([[[1, 2, 3],
        [4, 5, 6]]])

In [39]:
arr * arr

array([[[ 1,  4,  9],
        [16, 25, 36]]])

In [40]:
arr - arr

array([[[0, 0, 0],
        [0, 0, 0]]])

In [41]:
1 / arr

array([[[1.        , 0.5       , 0.33333333],
        [0.25      , 0.2       , 0.16666667]]])

In [42]:
arr ** 0.5

array([[[1.        , 1.41421356, 1.73205081],
        [2.        , 2.23606798, 2.44948974]]])

In [43]:
arr2 = np.array([[
    [1,1,1],
    [14,15,16]
]])
arr2 > arr

array([[[False, False, False],
        [ True,  True,  True]]])

In [44]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
arr[1:2]

array([1])

In [52]:
arr[1:3] = [11]
arr

array([ 0, 11, 11,  3,  4,  5,  6,  7,  8,  9])

In [53]:
arr = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [54]:
arr[1][2]

6

In [55]:
arr[1,2]

6

In [56]:
arr[:2, 1:]

array([[2, 3],
       [5, 6]])

In [57]:
arr[:2, 1:] = 0
arr

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

In [60]:
arr1 = np.arange(10)
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [59]:
arr2 = np.random.rand(10, 4)
arr2

array([[0.1183551 , 0.79991536, 0.81253399, 0.05390169],
       [0.91576851, 0.63711848, 0.78241706, 0.9660238 ],
       [0.35807204, 0.37916196, 0.05406099, 0.68672077],
       [0.26894506, 0.93129276, 0.99075769, 0.45831348],
       [0.9014268 , 0.3674674 , 0.026173  , 0.37965785],
       [0.63356151, 0.84020292, 0.38233923, 0.97003043],
       [0.07831305, 0.13696509, 0.30466385, 0.59392458],
       [0.89936023, 0.10529751, 0.70777383, 0.11482143],
       [0.4134196 , 0.63067838, 0.22900723, 0.89457664],
       [0.54353572, 0.73095065, 0.97201181, 0.82061427]])

In [61]:
arr2[arr1 > 5]

array([[0.07831305, 0.13696509, 0.30466385, 0.59392458],
       [0.89936023, 0.10529751, 0.70777383, 0.11482143],
       [0.4134196 , 0.63067838, 0.22900723, 0.89457664],
       [0.54353572, 0.73095065, 0.97201181, 0.82061427]])

In [62]:
arr2[arr1 > 5, 2:]

array([[0.30466385, 0.59392458],
       [0.70777383, 0.11482143],
       [0.22900723, 0.89457664],
       [0.97201181, 0.82061427]])

In [63]:
arr2[~(arr1 > 5)]

array([[0.1183551 , 0.79991536, 0.81253399, 0.05390169],
       [0.91576851, 0.63711848, 0.78241706, 0.9660238 ],
       [0.35807204, 0.37916196, 0.05406099, 0.68672077],
       [0.26894506, 0.93129276, 0.99075769, 0.45831348],
       [0.9014268 , 0.3674674 , 0.026173  , 0.37965785],
       [0.63356151, 0.84020292, 0.38233923, 0.97003043]])

In [64]:
arr2[(arr1 > 5) & (arr1 > 7)]

array([[0.4134196 , 0.63067838, 0.22900723, 0.89457664],
       [0.54353572, 0.73095065, 0.97201181, 0.82061427]])

In [66]:
arr2

array([[0.1183551 , 0.79991536, 0.81253399, 0.05390169],
       [0.91576851, 0.63711848, 0.78241706, 0.9660238 ],
       [0.35807204, 0.37916196, 0.05406099, 0.68672077],
       [0.26894506, 0.93129276, 0.99075769, 0.45831348],
       [0.9014268 , 0.3674674 , 0.026173  , 0.37965785],
       [0.63356151, 0.84020292, 0.38233923, 0.97003043],
       [0.07831305, 0.13696509, 0.30466385, 0.59392458],
       [0.89936023, 0.10529751, 0.70777383, 0.11482143],
       [0.4134196 , 0.63067838, 0.22900723, 0.89457664],
       [0.54353572, 0.73095065, 0.97201181, 0.82061427]])

In [67]:
arr2[arr2 > 0.5] = 0

In [68]:
arr2

array([[0.1183551 , 0.        , 0.        , 0.05390169],
       [0.        , 0.        , 0.        , 0.        ],
       [0.35807204, 0.37916196, 0.05406099, 0.        ],
       [0.26894506, 0.        , 0.        , 0.45831348],
       [0.        , 0.3674674 , 0.026173  , 0.37965785],
       [0.        , 0.        , 0.38233923, 0.        ],
       [0.07831305, 0.13696509, 0.30466385, 0.        ],
       [0.        , 0.10529751, 0.        , 0.11482143],
       [0.4134196 , 0.        , 0.22900723, 0.        ],
       [0.        , 0.        , 0.        , 0.        ]])

In [69]:
arr = np.empty((8, 4))
for i in range(8):
  arr[i] = i
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [70]:
arr[[4,3,0,6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [71]:
arr[[-3, -1, -5]]

array([[5., 5., 5., 5.],
       [7., 7., 7., 7.],
       [3., 3., 3., 3.]])

In [77]:
arr = np.arange(32).reshape((8 ,4))

In [78]:
arr[[1, 2, 3, 4], [0, 1,2,3]]

array([ 4,  9, 14, 19])

In [79]:
arr = np.arange(15).reshape(3, 5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [80]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [81]:
arr1 = arr.T
arr1

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [82]:
arr.dot(arr1)

array([[ 30,  80, 130],
       [ 80, 255, 430],
       [130, 430, 730]])

In [83]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [84]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [85]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [87]:
arr1 = np.random.randn(8)
arr1

array([ 0.46427998,  0.30056091, -0.95237002, -0.14278687,  0.51661186,
       -0.46865121, -0.69983409,  0.7897194 ])

In [88]:
arr2 = np.random.randn(8)
arr2

array([ 0.95170047, -0.27519313,  1.58954809, -0.11756187, -1.06630375,
        0.85746168, -0.56160697, -0.73485708])

In [89]:
np.maximum(arr1, arr2)

array([ 0.95170047,  0.30056091,  1.58954809, -0.11756187,  0.51661186,
        0.85746168, -0.56160697,  0.7897194 ])

In [90]:
arr = np.random.randn(10) * 5
arr

array([-2.30931244,  2.50923192,  1.56257651, -3.97553508, -8.59122974,
       -4.30961361,  5.96433822, -2.04856309,  0.97819903, -1.65436571])

In [91]:
remainder, whole_part = np.modf(arr)

In [92]:
remainder

array([-0.30931244,  0.50923192,  0.56257651, -0.97553508, -0.59122974,
       -0.30961361,  0.96433822, -0.04856309,  0.97819903, -0.65436571])

In [93]:
whole_part

array([-2.,  2.,  1., -3., -8., -4.,  5., -2.,  0., -1.])

In [94]:
points = np.arange(-5, 5, 0.01)
points

array([-5.0000000e+00, -4.9900000e+00, -4.9800000e+00, -4.9700000e+00,
       -4.9600000e+00, -4.9500000e+00, -4.9400000e+00, -4.9300000e+00,
       -4.9200000e+00, -4.9100000e+00, -4.9000000e+00, -4.8900000e+00,
       -4.8800000e+00, -4.8700000e+00, -4.8600000e+00, -4.8500000e+00,
       -4.8400000e+00, -4.8300000e+00, -4.8200000e+00, -4.8100000e+00,
       -4.8000000e+00, -4.7900000e+00, -4.7800000e+00, -4.7700000e+00,
       -4.7600000e+00, -4.7500000e+00, -4.7400000e+00, -4.7300000e+00,
       -4.7200000e+00, -4.7100000e+00, -4.7000000e+00, -4.6900000e+00,
       -4.6800000e+00, -4.6700000e+00, -4.6600000e+00, -4.6500000e+00,
       -4.6400000e+00, -4.6300000e+00, -4.6200000e+00, -4.6100000e+00,
       -4.6000000e+00, -4.5900000e+00, -4.5800000e+00, -4.5700000e+00,
       -4.5600000e+00, -4.5500000e+00, -4.5400000e+00, -4.5300000e+00,
       -4.5200000e+00, -4.5100000e+00, -4.5000000e+00, -4.4900000e+00,
       -4.4800000e+00, -4.4700000e+00, -4.4600000e+00, -4.4500000e+00,
      

In [95]:
xs, ys = np.meshgrid(points, points)

In [96]:
xs

array([[-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       ...,
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99]])

In [97]:
ys

array([[-5.  , -5.  , -5.  , ..., -5.  , -5.  , -5.  ],
       [-4.99, -4.99, -4.99, ..., -4.99, -4.99, -4.99],
       [-4.98, -4.98, -4.98, ..., -4.98, -4.98, -4.98],
       ...,
       [ 4.97,  4.97,  4.97, ...,  4.97,  4.97,  4.97],
       [ 4.98,  4.98,  4.98, ...,  4.98,  4.98,  4.98],
       [ 4.99,  4.99,  4.99, ...,  4.99,  4.99,  4.99]])

In [98]:
arr = np.random.randn(4,4)
arr > 0

array([[False,  True,  True, False],
       [ True, False,  True, False],
       [False,  True, False,  True],
       [False,  True,  True,  True]])

In [99]:
np.where(arr > 0, 2, -2)

array([[-2,  2,  2, -2],
       [ 2, -2,  2, -2],
       [-2,  2, -2,  2],
       [-2,  2,  2,  2]])

In [101]:
arr = np.arange(100).reshape(10, 10)
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [102]:
arr.mean(axis=1)

array([ 4.5, 14.5, 24.5, 34.5, 44.5, 54.5, 64.5, 74.5, 84.5, 94.5])

In [105]:
arr.mean(1)

array([ 4.5, 14.5, 24.5, 34.5, 44.5, 54.5, 64.5, 74.5, 84.5, 94.5])

In [106]:
arr.sum(axis=0)

array([450, 460, 470, 480, 490, 500, 510, 520, 530, 540])

In [107]:
arr.sum(0)

array([450, 460, 470, 480, 490, 500, 510, 520, 530, 540])

In [108]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [109]:
arr.cumsum()

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36, 45])

In [110]:
arr = np.random.randn(100)
arr

array([ 0.74134487, -0.92090187, -0.65332613, -0.99868172,  0.54133322,
       -1.37059113, -0.35145502,  0.38347479, -0.67436725,  0.48888977,
       -0.96138991, -0.3245434 ,  0.52503805,  1.67338141, -0.54198519,
        0.77129577,  0.32160869,  1.41344895, -0.92708879, -0.39530027,
        0.42025014, -1.07953058,  1.03823667, -0.36359181,  0.07350611,
        1.30086256, -0.49223384, -1.37996898,  1.57072798, -0.5035094 ,
        1.8697169 , -0.02036789, -1.02661893, -0.11481463, -0.94247591,
        0.46925579, -1.51731542, -1.3279088 , -0.38830492, -0.32811813,
       -1.54412351, -1.5723857 ,  1.13322505, -0.16592192,  0.15662391,
        1.41925421, -1.3293974 ,  1.00270827,  0.24803809, -1.25349529,
       -0.1605761 , -0.62957352,  1.04448003,  0.25726796,  0.13194744,
        0.79393462,  0.76361348,  0.4032076 , -2.02794146,  1.0740229 ,
        0.66411761, -0.57398006,  0.28131506, -3.02246571, -0.55163425,
       -0.63940255, -0.27422147,  0.22063869, -0.66876538, -1.13

In [111]:
arr > 0

array([ True, False, False, False,  True, False, False,  True, False,
        True, False, False,  True,  True, False,  True,  True,  True,
       False, False,  True, False,  True, False,  True,  True, False,
       False,  True, False,  True, False, False, False, False,  True,
       False, False, False, False, False, False,  True, False,  True,
        True, False,  True,  True, False, False, False,  True,  True,
        True,  True,  True,  True, False,  True,  True, False,  True,
       False, False, False, False,  True, False, False, False,  True,
        True,  True, False,  True, False,  True, False, False,  True,
        True,  True, False, False,  True,  True, False,  True,  True,
       False,  True,  True, False,  True,  True, False,  True, False,
        True])

In [113]:
(arr > 0).sum()

49

In [117]:
arr = np.array([False, False, True, False])

In [118]:
arr.any()

True

In [119]:
arr.all()

False

In [124]:
arr = np.random.randn(5, 3)
arr

array([[-0.17619946,  1.47879855,  1.19294929],
       [-0.29372729,  0.19047999, -0.03527924],
       [-0.59455181, -0.25797043, -0.95379494],
       [-0.58246937, -0.26866379,  0.67815171],
       [-0.14883239, -1.44124155, -1.29858973]])

In [125]:
arr.sort(1)
arr

array([[-0.17619946,  1.19294929,  1.47879855],
       [-0.29372729, -0.03527924,  0.19047999],
       [-0.95379494, -0.59455181, -0.25797043],
       [-0.58246937, -0.26866379,  0.67815171],
       [-1.44124155, -1.29858973, -0.14883239]])

In [127]:
arr = np.arange(100)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [129]:
arr[int(0.05 * len(arr))]

5

In [130]:
arr = np.array([1,1,1,2,2,2,3,3,3])
np.unique(arr)

array([1, 2, 3])

In [131]:
sorted(set(arr))

[1, 2, 3]

In [132]:
np.in1d(arr, [1])

array([ True,  True,  True, False, False, False, False, False, False])

In [133]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [134]:
np.save("file_name", arr)

In [136]:
np.load("file_name.npy")

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [147]:
np.savez("file_name.npz", a=arr, b=arr2)

In [148]:
np.load("file_name.npz")['a']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [149]:
np.savez_compressed("file_name2.npz", a=arr, b=arr2)

In [150]:
np.load("file_name2.npz")['a']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])